# Настройки проекта
name: AID
# Подключение всех пакетов SPM
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.7.1
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.9.0
options:
  bundleIdPrefix: com
# Список целей (таргетов)
targets:
  AID:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - package: SnapKit
        product: SnapKit
      - package: Alamofire
        product: Alamofire
    sources: [AID]
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        name: Run SwiftLint
        basedOnDependencyAnalysis: false
    # Конфигурация файла Info.plist
    info:
      path: AID/Application/Info.plist
      properties:
        NSAppTransportSecuritySettings:
            NSExceptionDomains:
                ai-dashboard.site:
                    NSIncludesSubdomains: true
                    NSExceptionAllowsInsecureHTTPLoads: true
        UIRequiresFullScreen: YES
        UIApplicationSceneManifest:
            UIApplicationSupportsMultipleScenes: false
            UISceneConfigurations:
              UIWindowSceneSessionRoleApplication:
                - UISceneConfigurationName: Default Configuration
                  UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchStoryboardName: LaunchScreen
