# Настройки проекта
name: AID
# Подключение всех пакетов SPM
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.7.1
options:
  bundleIdPrefix: com
# Список целей (таргетов)
targets:
  AID:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    dependencies:
      - package: SnapKit
        product: SnapKit
    sources: [AID]
    postCompileScripts:
      - scipt: swiftlint
        name: SwiftLint
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
    # Конфигурация файла Info.plist
    info:
      path: AID/Application/Info.plist
      properties:
        UIRequiresFullScreen: YES
        UIApplicationSceneManifest:
            UIApplicationSupportsMultipleScenes: false
            UISceneConfigurations:
              UIWindowSceneSessionRoleApplication:
                - UISceneConfigurationName: Default Configuration
                  UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchStoryboardName: LaunchScreen
