# Настройки проекта
name: AID
# Подключение всех пакетов SPM
packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.7.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    from: 5.9.0
options:
  bundleIdPrefix: ru
# Список целей (таргетов)
targets:
  StockInfo:
    type: app-extension
    platform: iOS
    deploymentTarget: "17.0"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: ru.AID.StockInfo
    dependencies:
      - package: Alamofire
        product: Alamofire
    sources: [StockInfo]
    info:
      path: StockInfo/Info.plist
      properties:
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        NSAppTransportSecurity:
          NSExceptionDomains:
            ai-dashboard.site:
              NSIncludesSubdomains: true
              NSExceptionAllowsInsecureHTTPLoads: true
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
  AID:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - package: SnapKit
        product: SnapKit
      - package: Alamofire
        product: Alamofire
      - target: StockInfo
    sources: [AID]
    postCompileScripts:
      - script: |
                if [[ "$(uname -m)" == arm64 ]]; then
                    export PATH="/opt/homebrew/bin:$PATH"
                fi

                if which swiftlint > /dev/null; then
                    swiftlint
                else
                    echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
                fi
        name: Run SwiftLint
        basedOnDependencyAnalysis: false
    # Конфигурация файла Info.plist
    info:
      path: AID/Application/Info.plist
      properties:
        NSAppTransportSecurity:
            NSExceptionDomains:
                ai-dashboard.site:
                    NSIncludesSubdomains: true
                    NSExceptionAllowsInsecureHTTPLoads: true
        UIRequiresFullScreen: YES
        UIApplicationSceneManifest:
            UIApplicationSupportsMultipleScenes: false
            UISceneConfigurations:
              UIWindowSceneSessionRoleApplication:
                - UISceneConfigurationName: Default Configuration
                  UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        UILaunchStoryboardName: LaunchScreen
  AIDUnitTests: # Цель для юнит-тестов
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - target: AID # Зависимость от основной цели вашего приложения
    sources: [AIDUnitTests] # Директория с исходными файлами тестов
    info:
      path: AID/Application/InfoForTest.plist
    scheme:
      - name: "AIDUnitTests"
      - target: AID

  AIDUITests: # Цель для UI-тестов
    type: bundle.ui-testing # Тип для UI-тестов
    platform: iOS
    deploymentTarget: "17.0"
    dependencies:
      - target: AID # Зависимость от основной цели вашего приложения
    sources: [AIDUITests] # Директория с исходными файлами UI-тестов
    info:
      path: AID/Application/InfoForTest.plist
    scheme:
      - name: "AIDUITests"
      - target: AID
