name: CI

on:
  push:
    branches:
      - tests

jobs:
  build:
    runs-on: macOS-13
    steps:

    - name: Select Xcode 15.2
      run: sudo xcode-select --switch /Applications/Xcode.app

    - name: check Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Install dependencies
      run: |
        brew install xcodegen

    - name: Generate Xcode project
      run: |
        make gen

    - name: Run unit tests
      run: |
        xcodebuild test -scheme AIDUnitTests -project AID.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' | xcpretty

    - name: Run UI tests
      run: |
        xcodebuild test -scheme AIDUITests -project AID.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' | xcpretty
