name: CI

on:
  push:
    branches:
      - tests

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install xcodegen
        
    - name: Generate Xcode project
      run: |
        make gen

    - name: Run unit tests
      run: |
        xcodebuild -project AID.xcodeproj -scheme AIDUnitTests -destination 'platform=iOS Simulator, OS=17.0.1,name=iPhone 15' test | xcpretty

    - name: Run UI tests
      run: |
        xcodebuild -project AID.xcodeproj -scheme AIDUITests -destination 'platform=iOS Simulator, OS=17.0.1,name=iPhone 15' test | xcpretty

