name: CI

on:
  push:
    branches:
      - tests

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        brew install xcodegen
        
    - name: Generate Xcode project
      run: |
        make gen

    -name: Set iOS Version
    run: |
        xcversion simulators --install='iOS 17.0'
    - name: Run unit tests
      run: |
        xcodebuild test -scheme AIDUnitTests -project AID.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' | xcpretty

    - name: Run UI tests
      run: |
        xcodebuild test -scheme AIDUITests -project AID.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.0' | xcpretty

